env:
  contexts:
  - name: CustomContext
    urls:
    - https://juice-shop.herokuapp.com/
    includePaths:
    - https://juice-shop.herokuapp.com/.*
    authentication:
      method: script
      parameters:
        script: /zap/wrk/scripts/authentication-mfa.py
        scriptEngine: jython
        mfaURL: https://juice-shop.herokuapp.com/rest/2fa/verify
        loginURL: https://juice-shop.herokuapp.com/rest/user/login
      verification:
        method: autodetect
        pollFrequency: 60
        pollUnits: requests
        pollUrl: ""
        pollPostData: ""
    sessionManagement:
      method: script
      parameters:
        script: /zap/wrk/scripts/authorization-header-session.py
        scriptEngine: jython
    technology: {}
    structure: {}
    users:
    - name: safeer@test.com
      credentials:
        email: safeer@test.com
        password: safeer
  parameters: {}
jobs:
- type: alertFilter
  parameters: {}
- type: passiveScan-config
  parameters: {}
- type: spiderAjax
  parameters:
    context: CustomContext
    user: safeer@test.com
    url: ""
    runOnlyIfModern: false
    maxDuration: 10 
  # tests:
  # - name: At least 100 URLs found
  #   type: stats
  #   onFail: INFO
  #   statistic: spiderAjax.urls.added
  #   operator: '>='
  #   value: 100
- type: activeScan
  parameters:
    context: CustomContext
    user: safeer@test.com
    policy: ""
    maxRuleDurationInMins: 0
    maxScanDurationInMins: 10 
    maxAlertsPerRule: 0
  policyDefinition:
    defaultStrength: medium
    defaultThreshold: medium
- type: report
  parameters:
    template: traditional-json
    theme: original
    reportDir: /zap/wrk
    reportFile: report.json
    reportTitle: ZAP Scanning Report
    reportDescription:  Detailed analysis of security vulnerabilities identified through ZAP (Zed Attack Proxy) scanning, including potential risks, recommended mitigations, and overall security posture evaluation.
    displayReport: false
  risks:
  - info
  - low
  - medium
  - high
  confidences:
  - falsepositive
  - low
  - medium
  - high
  - confirmed