name: DAST

on:
  push:
    branches:
      - main

jobs:
  docker-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Run Python container for updating mfa 
        run: |
          docker run -d -it --rm -v $(pwd):/wrk/:rw python:3.11-slim /bin/bash -c "pip install --no-cache-dir pyotp && python /wrk/scripts/mfa-gen.py"

      - name: Run ZAP container
        run: |
          docker run --rm -v $(pwd):/zap/wrk/:rw -u zap -i ghcr.io/zaproxy/zaproxy:stable zap.sh -addoninstall communityScripts -addoninstall jython -loglevel debug -cmd -autorun /zap/wrk/config-mfa.yaml

      - name: Uploading scan results
        env:
          TOKEN: ${{ secrets.ACCUKNOX_TOKEN }}
          END_POINT: "cspm.demo.accuknox.com"
          TENANT_ID: "167"
          LABEL: "SPOC"
        run: |
          curl --location --request POST "https://${END_POINT}/api/v1/artifact/?tenant_id=${TENANT_ID}&data_type=ZAP&label_id=${LABEL}&save_to_s3=false" --header "Tenant-Id: ${TENANT_ID}" --header "Authorization: Bearer ${TOKEN}" --form 'file=@"report.json"'
